version: '3.7'
services:
  movie_mania_front:
    ports:
      - 3000:3000
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
